export const blogs = [
  {
    id: 1,
    image: "/images/blogs/blog1.png",
    category: "Web Development",
    categoryBg: "#CFFAFE",
    categoryBorder: "#67E8F9",
    categoryText: "#06B6D4",
    date: "February 18, 2025",
    title: "SEO Optimization Tips for 2025",
    description:
      "Explore the emerging trends shaping the future of web development — from AI integrations to progressive ",
    authorImage: "/images/blogs/author2.png",
    authorName: "Ronald Richards",
    authorTitle: "Web Developer",
    readTime: "5 Min Read",
  },
  {
    id: 2,
    image: "/images/blogs/blog2.png",
    category: "SEO & Marketing",
    categoryBg: "#F3E8FF",
    categoryBorder: "#C4B5FD",
    categoryText: "#8B5CF6",
    date: "March 4, 2025",
    title: "Mastering SEO Strategies for 2025",
    description:
      "Learn the most effective SEO and marketing tactics that are redefining search engine success in the new age.",
    authorImage: "/images/blogs/author1.png",
    authorName: "Jenny Wilson",
    authorTitle: "SEO Specialist",
    readTime: "7 Min Read",
  },
  {
    id: 3,
    image: "/images/blogs/blog3.png",
    category: "Tech Trends",
    categoryBg: "#DCFCE7",
    categoryBorder: "#86EFAC",
    categoryText: "#22C55E",
    date: "April 1, 2025",
    title: "Top 10 Technologies to Watch in 2025",
    description:
      "Stay ahead of the curve with these cutting-edge technologies that are transforming industries ",
    authorImage: "/images/blogs/author3.png",
    authorName: "Darlene Robertson",
    authorTitle: "Tech Analyst",
    readTime: "6 Min Read",
  },
];
