import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

// SATOSHI FONT
const satoshi = localFont({
  src: [
    {
      path: "../../public/font/Satoshi-Regular.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../../public/font/Satoshi-Regular.otf",
      weight: "600",
      style: "semiBold",
    },
    {
      path: "../../public/font/Satoshi-Bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
  display: "swap",
  variable: "--font-satoshi",
});

// PLUS JAKARTA SANS
const plusJakartaSans = localFont({
  src: [
    {
      path: "../../public/font/static/PlusJakartaSans-Regular.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/font/static/PlusJakartaSans-SemiBold.ttf",
      weight: "600",
      style: "semiBold",
    },
    {
      path: "../../public/font/static/PlusJakartaSans-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  display: "swap",
  variable: "--font-plusjakarta",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${plusJakartaSans.variable} bg-white-base`}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
